config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # API routes
  defaults format: :json do
    mount_devise_token_auth_for 'User', at: 'login'
    resources :notifications, only: [:index, :show]
    resources :emergencies
    resources :posts
    resources :comments
    resources :exercises, only: [:index, :show]
    resources :conditions, only: [:index, :show]
    resources :post_tags, only: [:index, :show]
    resources :post_types, only: [:index, :show]
    resources :product_requests
    resources :products do
      resources :product_requests, path: "request"
    end
    resources :posts, only: [] do
      resources :comments
    end
    resources :profiles do
      post "/position", to: "profiles#position"
      resources :posts
      resources :conditions
      resources :exercises
    end
  end

    # Root web route
    root to: "admin/dashboard#index"

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :profile
  belongs_to :post
  has_one :notification
end

app/models/condition.rb
class Condition < ApplicationRecord
end

app/models/device_token.rb
class DeviceToken < ApplicationRecord
  belongs_to :user
end

app/models/emergency.rb
class Emergency < ApplicationRecord
  belongs_to :profile
  has_one :notification
end

app/models/exercise.rb
class Exercise < ApplicationRecord
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :post
  belongs_to :comment
  belongs_to :emergency
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :post_type
  belongs_to :profile
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
end

app/models/post_type.rb
class PostType < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :photo, ProductPhotoUploader
end

app/models/product_request.rb
class ProductRequest < ApplicationRecord
  belongs_to :profile
  belongs_to :product
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/profile_exercise.rb
class ProfileExercise < ApplicationRecord
  belongs_to :profile
  belongs_to :exercise
end

app/models/tag_of_post.rb
class TagOfPost < ApplicationRecord
  belongs_to :post
  belongs_to :post_tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  include DeviseTokenAuth::Concerns::User
end

app/controllers/product_requests_controller.rb
class ProductRequestsController < ApiController
  before_action :set_product_request, only: [:show, :edit, :update, :destroy]

  # GET /product_requests
  # GET /product_requests.json
  def index
    @product_requests = ProductRequest.all
  end

  # GET /product_requests/1
  # GET /product_requests/1.json
  def show
  end

  # GET /product_requests/new
  def new
    @product_request = ProductRequest.new
  end

  # GET /product_requests/1/edit
  def edit
  end

  # POST /product_requests
  # POST /product_requests.json
  def create
    @product_request = ProductRequest.new(product_request_params)

    respond_to do |format|
      if @product_request.save
        format.html { redirect_to @product_request, notice: 'Product request was successfully created.' }
        format.json { render :show, status: :created, location: @product_request }
      else
        format.html { render :new }
        format.json { render json: @product_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_requests/1
  # PATCH/PUT /product_requests/1.json
  def update
    respond_to do |format|
      if @product_request.update(product_request_params)
        format.html { redirect_to @product_request, notice: 'Product request was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_request }
      else
        format.html { render :edit }
        format.json { render json: @product_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_requests/1
  # DELETE /product_requests/1.json
  def destroy
    @product_request.destroy
    respond_to do |format|
      format.html { redirect_to product_requests_url, notice: 'Product request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_request
      @product_request = ProductRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_request_params
      params.permit(:profile_id, :product_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/product_requests_helper.rb
module ProductRequestsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/product_requests/_form.html.erb
<%= form_with(model: product_request, local: true) do |form| %>
  <% if product_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product_request.errors.count, "error") %> prohibited this product_request from being saved:</h2>

      <ul>
      <% product_request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :profile_id %>
    <%= form.text_field :profile_id %>
  </div>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.text_field :product_id %>
  </div>

  <div class="field">
    <%= form.label :pending %>
    <%= form.check_box :pending %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/product_requests/edit.html.erb
<h1>Editing Product Request</h1>

<%= render 'form', product_request: @product_request %>

<%= link_to 'Show', @product_request %> |
<%= link_to 'Back', product_requests_path %>

app/views/product_requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Product Requests</h1>

<table>
  <thead>
    <tr>
      <th>Profile</th>
      <th>Product</th>
      <th>Pending</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @product_requests.each do |product_request| %>
      <tr>
        <td><%= product_request.profile %></td>
        <td><%= product_request.product %></td>
        <td><%= product_request.pending %></td>
        <td><%= link_to 'Show', product_request %></td>
        <td><%= link_to 'Edit', edit_product_request_path(product_request) %></td>
        <td><%= link_to 'Destroy', product_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product Request', new_product_request_path %>

app/views/product_requests/new.html.erb
<h1>New Product Request</h1>

<%= render 'form', product_request: @product_request %>

<%= link_to 'Back', product_requests_path %>

app/views/product_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Profile:</strong>
  <%= @product_request.profile %>
</p>

<p>
  <strong>Product:</strong>
  <%= @product_request.product %>
</p>

<p>
  <strong>Pending:</strong>
  <%= @product_request.pending %>
</p>

<%= link_to 'Edit', edit_product_request_path(@product_request) %> |
<%= link_to 'Back', product_requests_path %>