config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # API routes
  defaults format: :json do
    mount_devise_token_auth_for 'User', at: 'login'
    resources :notifications, only: [:index, :show]
    resources :emergencies
    resources :posts
    resources :comments
    resources :exercises, only: [:index, :show]
    resources :conditions, only: [:index, :show]
    resources :post_tags, only: [:index, :show]
    resources :post_types, only: [:index, :show]
    resources :product_requests
    resources :products do
      resources :product_requests, path: "request"
    end
    resources :posts, only: [] do
      resources :comments
    end
    resources :profiles do
      post "/position", to: "profiles#position"
      resources :posts
      resources :conditions
      resources :exercises
    end
  end

    # Root web route
    root to: "admin/dashboard#index"

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :profile
  belongs_to :post
  has_one :notification
end

app/models/condition.rb
class Condition < ApplicationRecord
end

app/models/device_token.rb
class DeviceToken < ApplicationRecord
  belongs_to :user
end

app/models/emergency.rb
class Emergency < ApplicationRecord
  belongs_to :profile
  has_one :notification
end

app/models/exercise.rb
class Exercise < ApplicationRecord
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :post
  belongs_to :comment
  belongs_to :emergency
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :post_type
  belongs_to :profile
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
end

app/models/post_type.rb
class PostType < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :photo, ProductPhotoUploader
end

app/models/product_request.rb
class ProductRequest < ApplicationRecord
  belongs_to :profile
  belongs_to :product
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/profile_exercise.rb
class ProfileExercise < ApplicationRecord
  belongs_to :profile
  belongs_to :exercise
end

app/models/tag_of_post.rb
class TagOfPost < ApplicationRecord
  belongs_to :post
  belongs_to :post_tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  include DeviseTokenAuth::Concerns::User
end

app/controllers/notifications_controller.rb
class NotificationsController < ApiController
  before_action :set_notification, only: [:show, :edit, :update, :destroy]

  # GET /notifications
  # GET /notifications.json
  def index
    @notifications = Notification.all
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show
  end

  # GET /notifications/new
  def new
    @notification = Notification.new
  end

  # GET /notifications/1/edit
  def edit
  end

  # POST /notifications
  # POST /notifications.json
  def create
    @notification = Notification.new(notification_params)

    respond_to do |format|
      if @notification.save
        format.html { redirect_to @notification, notice: 'Notification was successfully created.' }
        format.json { render :show, status: :created, location: @notification }
      else
        format.html { render :new }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notifications/1
  # PATCH/PUT /notifications/1.json
  def update
    respond_to do |format|
      if @notification.update(notification_params)
        format.html { redirect_to @notification, notice: 'Notification was successfully updated.' }
        format.json { render :show, status: :ok, location: @notification }
      else
        format.html { render :edit }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification.destroy
    respond_to do |format|
      format.html { redirect_to notifications_url, notice: 'Notification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notification_params
      params.require(:notification).permit(:title, :content, :post_id, :comment_id, :emergency_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/notifications/_form.html.erb
<%= form_with(model: notification, local: true) do |form| %>
  <% if notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
      <% notification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="field">
    <%= form.label :post_id %>
    <%= form.text_field :post_id %>
  </div>

  <div class="field">
    <%= form.label :comment_id %>
    <%= form.text_field :comment_id %>
  </div>

  <div class="field">
    <%= form.label :emergency_id %>
    <%= form.text_field :emergency_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/notifications/edit.html.erb
<h1>Editing Notification</h1>

<%= render 'form', notification: @notification %>

<%= link_to 'Show', @notification %> |
<%= link_to 'Back', notifications_path %>

app/views/notifications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notifications</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Post</th>
      <th>Comment</th>
      <th>Emergency</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notifications.each do |notification| %>
      <tr>
        <td><%= notification.title %></td>
        <td><%= notification.content %></td>
        <td><%= notification.post %></td>
        <td><%= notification.comment %></td>
        <td><%= notification.emergency %></td>
        <td><%= link_to 'Show', notification %></td>
        <td><%= link_to 'Edit', edit_notification_path(notification) %></td>
        <td><%= link_to 'Destroy', notification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notification', new_notification_path %>

app/views/notifications/new.html.erb
<h1>New Notification</h1>

<%= render 'form', notification: @notification %>

<%= link_to 'Back', notifications_path %>

app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @notification.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @notification.content %>
</p>

<p>
  <strong>Post:</strong>
  <%= @notification.post %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @notification.comment %>
</p>

<p>
  <strong>Emergency:</strong>
  <%= @notification.emergency %>
</p>

<%= link_to 'Edit', edit_notification_path(@notification) %> |
<%= link_to 'Back', notifications_path %>