config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # API routes
  defaults format: :json do
    mount_devise_token_auth_for 'User', at: 'login'
    resources :notifications, only: [:index, :show]
    resources :emergencies
    resources :posts
    resources :comments
    resources :exercises, only: [:index, :show]
    resources :conditions, only: [:index, :show]
    resources :post_tags, only: [:index, :show]
    resources :post_types, only: [:index, :show]
    resources :product_requests
    resources :products do
      resources :product_requests, path: "request"
    end
    resources :posts, only: [] do
      resources :comments
    end
    resources :profiles do
      post "/position", to: "profiles#position"
      resources :posts
      resources :conditions
      resources :exercises
    end
  end

    # Root web route
    root to: "admin/dashboard#index"

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :profile
  belongs_to :post
  has_one :notification
end

app/models/condition.rb
class Condition < ApplicationRecord
end

app/models/device_token.rb
class DeviceToken < ApplicationRecord
  belongs_to :user
end

app/models/emergency.rb
class Emergency < ApplicationRecord
  belongs_to :profile
  has_one :notification
end

app/models/exercise.rb
class Exercise < ApplicationRecord
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :post
  belongs_to :comment
  belongs_to :emergency
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :post_type
  belongs_to :profile
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
end

app/models/post_type.rb
class PostType < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :photo, ProductPhotoUploader
end

app/models/product_request.rb
class ProductRequest < ApplicationRecord
  belongs_to :profile
  belongs_to :product
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/profile_exercise.rb
class ProfileExercise < ApplicationRecord
  belongs_to :profile
  belongs_to :exercise
end

app/models/tag_of_post.rb
class TagOfPost < ApplicationRecord
  belongs_to :post
  belongs_to :post_tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  include DeviseTokenAuth::Concerns::User
end

app/controllers/emergencies_controller.rb
class EmergenciesController < ApiController
  before_action :set_emergency, only: [:show, :edit, :update, :destroy]

  # GET /emergencies
  # GET /emergencies.json
  def index
    @emergencies = Emergency.all
  end

  # GET /emergencies/1
  # GET /emergencies/1.json
  def show
  end

  # GET /emergencies/new
  def new
    @emergency = Emergency.new
  end

  # GET /emergencies/1/edit
  def edit
  end

  # POST /emergencies
  # POST /emergencies.json
  def create
    @emergency = Emergency.new(emergency_params)

    respond_to do |format|
      if @emergency.save
        format.html { redirect_to @emergency, notice: 'Emergency was successfully created.' }
        format.json { render :show, status: :created, location: @emergency }
      else
        format.html { render :new }
        format.json { render json: @emergency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /emergencies/1
  # PATCH/PUT /emergencies/1.json
  def update
    respond_to do |format|
      if @emergency.update(emergency_params)
        format.html { redirect_to @emergency, notice: 'Emergency was successfully updated.' }
        format.json { render :show, status: :ok, location: @emergency }
      else
        format.html { render :edit }
        format.json { render json: @emergency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /emergencies/1
  # DELETE /emergencies/1.json
  def destroy
    @emergency.destroy
    respond_to do |format|
      format.html { redirect_to emergencies_url, notice: 'Emergency was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_emergency
      @emergency = Emergency.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def emergency_params
      params.require(:emergency).permit(:profile_id, :longitude, :latitude)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/emergencies_helper.rb
module EmergenciesHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/emergencies/_form.html.erb
<%= form_with(model: emergency, local: true) do |form| %>
  <% if emergency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(emergency.errors.count, "error") %> prohibited this emergency from being saved:</h2>

      <ul>
      <% emergency.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :profile_id %>
    <%= form.text_field :profile_id %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/emergencies/edit.html.erb
<h1>Editing Emergency</h1>

<%= render 'form', emergency: @emergency %>

<%= link_to 'Show', @emergency %> |
<%= link_to 'Back', emergencies_path %>

app/views/emergencies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Emergencies</h1>

<table>
  <thead>
    <tr>
      <th>Profile</th>
      <th>Longitude</th>
      <th>Latitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @emergencies.each do |emergency| %>
      <tr>
        <td><%= emergency.profile %></td>
        <td><%= emergency.longitude %></td>
        <td><%= emergency.latitude %></td>
        <td><%= link_to 'Show', emergency %></td>
        <td><%= link_to 'Edit', edit_emergency_path(emergency) %></td>
        <td><%= link_to 'Destroy', emergency, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Emergency', new_emergency_path %>

app/views/emergencies/new.html.erb
<h1>New Emergency</h1>

<%= render 'form', emergency: @emergency %>

<%= link_to 'Back', emergencies_path %>

app/views/emergencies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Profile:</strong>
  <%= @emergency.profile %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @emergency.longitude %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @emergency.latitude %>
</p>

<%= link_to 'Edit', edit_emergency_path(@emergency) %> |
<%= link_to 'Back', emergencies_path %>