config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # API routes
  defaults format: :json do
    mount_devise_token_auth_for 'User', at: 'login'
    resources :notifications, only: [:index, :show]
    resources :emergencies
    resources :posts
    resources :comments
    resources :exercises, only: [:index, :show]
    resources :conditions, only: [:index, :show]
    resources :post_tags, only: [:index, :show]
    resources :post_types, only: [:index, :show]
    resources :product_requests
    resources :products do
      resources :product_requests, path: "request"
    end
    resources :posts, only: [] do
      resources :comments
    end
    resources :profiles do
      post "/position", to: "profiles#position"
      resources :posts
      resources :conditions
      resources :exercises
    end
  end

    # Root web route
    root to: "admin/dashboard#index"

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :profile
  belongs_to :post
  has_one :notification
end

app/models/condition.rb
class Condition < ApplicationRecord
end

app/models/device_token.rb
class DeviceToken < ApplicationRecord
  belongs_to :user
end

app/models/emergency.rb
class Emergency < ApplicationRecord
  belongs_to :profile
  has_one :notification
end

app/models/exercise.rb
class Exercise < ApplicationRecord
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :post
  belongs_to :comment
  belongs_to :emergency
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :post_type
  belongs_to :profile
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
end

app/models/post_type.rb
class PostType < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :photo, ProductPhotoUploader
end

app/models/product_request.rb
class ProductRequest < ApplicationRecord
  belongs_to :profile
  belongs_to :product
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/profile_exercise.rb
class ProfileExercise < ApplicationRecord
  belongs_to :profile
  belongs_to :exercise
end

app/models/tag_of_post.rb
class TagOfPost < ApplicationRecord
  belongs_to :post
  belongs_to :post_tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  include DeviseTokenAuth::Concerns::User
end

app/controllers/post_tags_controller.rb
class PostTagsController < ApiController
  before_action :set_post_tag, only: [:show, :edit, :update, :destroy]

  # GET /post_tags
  # GET /post_tags.json
  def index
    @post_tags = PostTag.all
  end

  # GET /post_tags/1
  # GET /post_tags/1.json
  def show
  end

  # GET /post_tags/new
  def new
    @post_tag = PostTag.new
  end

  # GET /post_tags/1/edit
  def edit
  end

  # POST /post_tags
  # POST /post_tags.json
  def create
    @post_tag = PostTag.new(post_tag_params)

    respond_to do |format|
      if @post_tag.save
        format.html { redirect_to @post_tag, notice: 'Post tag was successfully created.' }
        format.json { render :show, status: :created, location: @post_tag }
      else
        format.html { render :new }
        format.json { render json: @post_tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /post_tags/1
  # PATCH/PUT /post_tags/1.json
  def update
    respond_to do |format|
      if @post_tag.update(post_tag_params)
        format.html { redirect_to @post_tag, notice: 'Post tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @post_tag }
      else
        format.html { render :edit }
        format.json { render json: @post_tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /post_tags/1
  # DELETE /post_tags/1.json
  def destroy
    @post_tag.destroy
    respond_to do |format|
      format.html { redirect_to post_tags_url, notice: 'Post tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post_tag
      @post_tag = PostTag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_tag_params
      params.require(:post_tag).permit(:name)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/post_tags_helper.rb
module PostTagsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/post_tags/_form.html.erb
<%= form_with(model: post_tag, local: true) do |form| %>
  <% if post_tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post_tag.errors.count, "error") %> prohibited this post_tag from being saved:</h2>

      <ul>
      <% post_tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/post_tags/edit.html.erb
<h1>Editing Post Tag</h1>

<%= render 'form', post_tag: @post_tag %>

<%= link_to 'Show', @post_tag %> |
<%= link_to 'Back', post_tags_path %>

app/views/post_tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Post Tags</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @post_tags.each do |post_tag| %>
      <tr>
        <td><%= post_tag.name %></td>
        <td><%= link_to 'Show', post_tag %></td>
        <td><%= link_to 'Edit', edit_post_tag_path(post_tag) %></td>
        <td><%= link_to 'Destroy', post_tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post Tag', new_post_tag_path %>

app/views/post_tags/new.html.erb
<h1>New Post Tag</h1>

<%= render 'form', post_tag: @post_tag %>

<%= link_to 'Back', post_tags_path %>

app/views/post_tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @post_tag.name %>
</p>

<%= link_to 'Edit', edit_post_tag_path(@post_tag) %> |
<%= link_to 'Back', post_tags_path %>